CREATE TABLE IF NOT EXISTS hotels (
    hotel_id VARCHAR(40) PRIMARY KEY,
    location_code VARCHAR(10) NOT NULL,
    location_name VARCHAR(100) NOT NULL,
    name VARCHAR(160) NOT NULL,
    price_per_night DECIMAL(15, 2) NOT NULL,
    rating DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS hotel_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_code VARCHAR(64) NOT NULL UNIQUE,
    hotel_id VARCHAR(40) NOT NULL,
    guest_name VARCHAR(150) NOT NULL,
    check_in_date DATE NOT NULL,
    nights INTEGER NOT NULL CHECK (nights > 0),
    status VARCHAR(30) NOT NULL,
    total_amount DECIMAL(15, 2) NOT NULL,
    reserved_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_reservation_hotel FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id)
);
