CREATE TABLE IF NOT EXISTS flights (
    flight_id VARCHAR(40) PRIMARY KEY,
    origin_code VARCHAR(10) NOT NULL,
    origin_city VARCHAR(100) NOT NULL,
    destination_code VARCHAR(10) NOT NULL,
    destination_city VARCHAR(100) NOT NULL,
    departure_date DATE NOT NULL,
    airline VARCHAR(100) NOT NULL,
    price DECIMAL(15, 2) NOT NULL,
    departure_time TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS flight_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(64) NOT NULL UNIQUE,
    flight_id VARCHAR(40) NOT NULL,
    passenger_name VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_amount DECIMAL(15, 2) NOT NULL,
    booked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_flight_booking_flight FOREIGN KEY (flight_id) REFERENCES flights(flight_id)
);
